name: Compile Latex and Release PDF

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '38 5,16 * * *'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
          pdflatex --shell-escape main.tex
          makeglossaries main
          biber main
          pdflatex --shell-escape main.tex
          pdflatex --shell-escape main.tex    
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Normal PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: main.pdf
          asset_content_type: pdf
